import {
    constants,
    theme,
    COLORS,
    darkTheme,
    lightTheme,
    images,
    icons,
    dummyData,
    
} from '../../constants';
import { StyleSheet } from 'react-native';
import { FONTS, SIZES } from '../../constants/theme';
 
const styles=(selectedTheme:any)=>StyleSheet.create({
    container:{
        flex:1,
        paddingTop:10,
        
        backgroundColor:selectedTheme.backgroundColor1
    },
    upperContainer:{
     
    },
    upperHeaderContainer:{
        flexDirection:'row',
        paddingHorizontal:10,
        alignItems:'center',
        justifyContent:'space-between'
    },

    upperHeaderLeftContainer:{
        flexDirection:'row',
        alignItems:'center',
    },
    mediaIcon:{
        height:30,
        width:30,
        resizeMode:'contain',
        tintColor:selectedTheme.tintColor
    },
    favoriteIcon:{
        height:30,
        width:30,
        resizeMode:'contain',
        marginLeft:20,
    },
    lowerContainer:{
        flex:1
    },
    lowerUpperContainer:{
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center',
        borderBottomWidth:1,
        borderColor:selectedTheme.lineDivider,
    },
    titleText:{
        ...FONTS.h3,
        color:selectedTheme.textColor,
        textAlign:'center'
    },
    titleButton:{
        flex:1,
        borderColor:COLORS.primary,
        paddingVertical:15
    },

    instructorProfileImage:{
        height:50,
        width:50,
        borderRadius:180,
    },
    chapterIcon:{
        height:40,
        width:40,
    },
    lockChapterIcon:{
        height:20,
        width:20,
        
        tintColor:COLORS.white
    },
    lockChapterIconContainer:{
        padding:10,
        borderRadius:180,
        backgroundColor:COLORS.gray40
    },
    videoListContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginVertical:10,
    },
    videoInnerListContainer:{
        flexDirection:'row',
        alignItems:'center'
    },
    downloadedIcon:{
        height:30,
        width:30,
        resizeMode:'contain',
        marginLeft:10,
    },
    headText:{
        ...FONTS.h2,
        color:selectedTheme.textColor,
        width:'75%'
    },
    selectedContainer:{
        padding:10,
    },
    studentTimeContainer:{
        flexDirection:'row',
        alignItems:'center',
        paddingVertical:5
    }, 
    timeContainer:{
        flexDirection:'row',
        alignItems:'center',    
    },
    timeIcon:{
        height:20,
        width:20,
        resizeMode:'contain',
        marginLeft:10,
        marginRight:5
    },
    instructorContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        borderBottomWidth:1,
        borderBottomColor:selectedTheme.lineDivider,
        marginVertical:10,
        paddingBottom:5,

    },
    instructorLeftContainer:{
        flexDirection:'row',
        alignItems:'center'
    },
    instructorInnerContainer:{
        paddingLeft:10,
    },
    downloadContainer:{
        flexDirection:'row',
        alignItems:'center'
    },
    smallLabelText:{
        ...FONTS.h5,
        color:selectedTheme.textColor3
    },
    labelText:{
        ...FONTS.h4,
        color:selectedTheme.textColor3,
        textAlign:'right'
    },
    instructorText:{
        ...FONTS.h3,
        color:selectedTheme.textColor,
    },
    followButton:{
        backgroundColor:COLORS.primary,
        paddingVertical:5,
        paddingHorizontal:10,
        borderRadius:15
    },
    followButtonText:{
        color:COLORS.white,
        ...FONTS.h3
    },
    videoTitleText:{
        ...FONTS.h3,
        color:selectedTheme.textColor
    },
    videoListTextContainer:{
        marginLeft:10,
    },
    renderContainer3:{
        flexDirection:'row',
        marginVertical:10,
        
    },

    render3MainImage:{
        width:SIZES.width*0.35,
        padding:10
        
    },
    render3FavouriteButton:{
        alignSelf:'flex-end',
        padding:5,
        backgroundColor:COLORS.white,
        borderRadius:5
    },
    heartIcon:{
        height:20,
        width:20,
        resizeMode:'contain'
    },
    render3TitleText:{
        paddingHorizontal:10,
        width:SIZES.width*0.5,
        ...FONTS.h3,
        color:selectedTheme.textColor
    },
    render3InnerContainer:{
        flexDirection:'row',
        alignItems:'center'
    },
    render3InstructorText:{
        paddingLeft:10,
        ...FONTS.h4,
        color:selectedTheme.textColor3
    },
    render3DurationContainer:{
        flexDirection:'row',
        paddingLeft:5,
        alignItems:'center'
    },
    render3ClockIcon:{
        height:18,
        width:18,
        resizeMode:'contain',
        tintColor:COLORS.gray40
    },
    render3DurationText:{
        paddingLeft:5,
        ...FONTS.h4,
        color:selectedTheme.textColor3
    },
    render3InnerLowerContainer:{
        flexDirection:'row',
        paddingLeft:10,
        alignItems:'center'
    },
    render3RatingIcon:{
        height:20,
        width:20,
        resizeMode:'contain'
    },
    render3RatingContainer:{
        flexDirection:'row',
        paddingLeft:10,
        alignItems:'center'
    },
    render3ItemSeprator:{
        marginVertical:10
    },
    render3PriceText:{
        ...FONTS.h2,
        color:COLORS.primary
    },
    render3RatingText:{
        ...FONTS.h4,
        paddingLeft:5,
        color:selectedTheme.textColor
    },
    midContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginVertical:10,
    },
    seeAllButton:{
        backgroundColor:COLORS.primary,
        paddingVertical:5,
        paddingHorizontal:10,
        borderRadius:15,
    },
    seeAllText:{
        ...FONTS.h3,
        color:COLORS.white
    }

})
export default styles