const icon = {
  profile: require('../../assets/profile.png'),
  padlock: require('../../assets/padlock.png'),
  communication: require('../../assets/communication.png'),
  translate: require('../../assets/translate.png'),
  logout: require('../../assets/logout.png'),
  lock: require('../../assets/lock.png'),
  left_arrow: require('../../assets/left_arrow.png'),
  right_arrow: require('../../assets/right_arrow.png'),
  help: require('../../assets/help.png'),
  home: require('../../assets/home.png'),
  progress: require('../../assets/progress.png'),
  inbox: require('../../assets/inbox.png'),
  setting: require('../../assets/settings.png'),
  header: require('../../assets/header.png'),
  logo: require('../../assets/logo.png'),
  courseImage: require('../../assets/courseImage.jpg'),
  camera: require('../../assets/camera.png'),
  gallery: require('../../assets/gallery.png'),
  cancel: require('../../assets/cancel.png'),
  profileImage: 'https://kaushalgupta.netlify.app/img/kaushal-quote2.jpg',
  course_main: require('../../assets/course_main.png'),
  foodImage: require('../../assets/foodImage.jpg'),
  clock: require('../../assets/clock.png'),
  boookmark:require('../../assets/bookmark.png'),
  bookmark_saved:require('../../assets/bookmark_saved.png'),
  close:require('../../assets/close.png')
};
export default icon;
