import { StyleSheet } from "react-native";
import { COLORS } from "../../constants";
const styles= StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:COLORS.primary,
        padding:10,
    },
    renderContainer:{
        flexDirection:'row',
        alignItems:'center',
        paddingVertical:15,
    },
    icon:{
        resizeMode:'contain',
        height:25,
        width:25,
        tintColor:COLORS.white
    },
    iconText:{
        color:COLORS.white,
        fontSize:18,
        fontWeight:'700',
        paddingHorizontal:10,
    },
    lineContainer:{
        height:2,
        width:'100%',
        backgroundColor:COLORS.white,
        marginVertical:10,
    },
    closeIcon:{
        height:25,
        width:25,
        resizeMode:'contain',
        tintColor:COLORS.white
    },
    profileIcon:{
        height:50,
        width:50,
        borderRadius:10,
    },
    upperContainer:{
        flexDirection:'row',
        alignItems:'center',
        marginVertical:20,
    },
    nameText:{
        color:COLORS.white,
        fontSize:18,
        fontWeight:'600',
        paddingHorizontal:10,
        
    },
    labelText:{
        color:COLORS.white2,
        fontSize:16,
        paddingHorizontal:10,
        
    },
    modalContainer2:{
        flex:1
    },

    modalHeader2:{
        backgroundColor:COLORS.transparentBlack7,
        flex:0.8
    },
    modalFooter2:{
        alignItems:'center',
        flex:0.2,
        flexDirection:'row',
        backgroundColor:COLORS.white,
        justifyContent:'space-between',
        paddingHorizontal:20,
    },
    modalText2:{
        color:COLORS.primary    ,
        fontSize:16,
        fontWeight:'600'
    },
    modalIconText2:{
        justifyContent:'center',
        alignItems:'center'
    },
    modalIcon2:{
        height:30,
        width:30,
        resizeMode:"contain",
        tintColor:COLORS.primary
    },
})
export default styles;