import {

    COLORS,
    
} from '../../constants';
import { StyleSheet } from 'react-native';
import { FONTS, SIZES } from '../../constants/theme';

const styles = (selectedTheme:any)=>StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:selectedTheme.backgroundColor1
    },
    backgroundImage:{
        paddingLeft:10,
        flex:1/3,
        paddingTop:10,
    
    },
    wrapperContainer:{
        flex:2/3,
        padding:10
    },
    innerUpperContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        flex:1,
    },
    titleText:{
        ...FONTS.h1,
        paddingLeft:20,
        color:COLORS.white
    },
    mobileImage:{
        height:"100%",
        width:'60%',
        resizeMode:'contain',
    },
    midContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginVertical:10,
    },
    labelText:{
        ...FONTS.h3,
        color:selectedTheme.textColor3
    },
    filterButton:{
        backgroundColor:COLORS.primary,
        padding:10,
        borderRadius:10,
    },
    filterImage:{
        tintColor:selectedTheme.tintColor,
        height:20,
        width:20,
        resizeMode:'contain'
    },
    renderContainer3:{
        flexDirection:'row'
    },
    render3MainImage:{
        width:SIZES.width*0.35,
        padding:10
        
    },
    render3FavouriteButton:{
        alignSelf:'flex-end',
        padding:5,
        backgroundColor:COLORS.white,
        borderRadius:5
    },
    heartIcon:{
        height:20,
        width:20,
        resizeMode:'contain'
    },
    render3TitleText:{
        paddingHorizontal:10,
        width:SIZES.width*0.5,
        ...FONTS.h3,
        color:selectedTheme.textColor
    },
    render3InnerContainer:{
        flexDirection:'row',
        alignItems:'center'
    },
    render3InstructorText:{
        paddingLeft:10,
        ...FONTS.h4,
        color:selectedTheme.textColor3
    },
    render3DurationContainer:{
        flexDirection:'row',
        paddingLeft:5,
        alignItems:'center'
    },
    render3ClockIcon:{
        height:18,
        width:18,
        resizeMode:'contain',
        tintColor:COLORS.gray40
    },
    render3DurationText:{
        paddingLeft:5,
        ...FONTS.h4,
        color:selectedTheme.textColor3
    },
    render3InnerLowerContainer:{
        flexDirection:'row',
        paddingLeft:10,
        alignItems:'center'
    },
    render3RatingIcon:{
        height:20,
        width:20,
        resizeMode:'contain'
    },
    render3RatingContainer:{
        flexDirection:'row',
        paddingLeft:10,
        alignItems:'center'
    },
    render3ItemSeprator:{
        marginVertical:10
    },
    render3PriceText:{
        ...FONTS.h2,
        color:COLORS.primary
    },
    render3RatingText:{
        ...FONTS.h4,
        paddingLeft:5,
        color:selectedTheme.textColor
    },
    filterContainer:{
            flex:1
    },
    filterUpperContainer:{
        flex:0.1,
        backgroundColor:COLORS.transparentBlack7
    },
    filterBottomContainer:{
        flex:0.9,
        backgroundColor:selectedTheme.backgroundColor1,
        padding:10,
    },
    filterBottomUpContainer:{
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center'
    },
    headText:{
        ...FONTS.h1,
        color:selectedTheme.textColor
    },
    filterInnerContainer:{
        flex:1
    },
    cancelButton:{
        width:50,
        
    },
    cancelText:{
        ...FONTS.h3,
        color:selectedTheme.textColor3
    },
    filterTitle:{
        fontSize:18,
        fontFamily: "Roboto-Bold",
        lineHeight: 22 ,
        color:selectedTheme.name=="dark"?COLORS.gray20:COLORS.primary3,
        paddingVertical:10,
    },
    classTypeContainer:{
        flexDirection:'row'
    },
    classTypeImage:{
        tintColor:COLORS.gray40,
        height:30,
        width:30,
    },
    classTypeButton:{
        borderColor:selectedTheme.lineDivider,
        borderWidth:2,
        borderRadius:10,
        padding:10,
        alignItems:'center',
        justifyContent:'center',
        margin:"1%",
        width:94/3+'%'
    },
    classTypeText:{
        ...FONTS.h3,
        paddingTop:5,
        color:COLORS.gray40
    
    },
    classLevelContainer:{
        alignItems:'center',
        flexDirection:'row',
        justifyContent:'space-between',
        borderBottomWidth:1,
        borderColor:selectedTheme.lineDivider,
        paddingVertical:5
    },
    checkIcon:{
        height:25,
        width:25,
        resizeMode:'contain'
    },
    checkIconWrapper:{
        height:35,
        width:35,
        borderWidth:1,
        borderColor:selectedTheme.lineDivider,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:10,
    },
    classLevelText:{
        ...FONTS.h3,
        color:selectedTheme.name=="dark"?COLORS.gray20:COLORS.primary3,
    },
    createdWithinContainer:{
        flexDirection:'row',
        marginVertical:5,
    },
    innerCreatedWithinContainer:{
        paddingHorizontal:10,
        paddingVertical:5,
        borderWidth:1,
        borderColor:selectedTheme.lineDivider,
        marginRight:10,
        borderRadius:10,
    },
    createdWithinText:{
        ...FONTS.h3,
        color:selectedTheme.name=="dark"?COLORS.gray20:COLORS.primary3,
    },
    buttonContainer:{
       
        flexDirection:'row',
        justifyContent:'space-between'
    },
    button:{
        paddingVertical:10,
        borderWidth:2,
        width:'48%',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:10,
        borderColor:selectedTheme.lineDivider
    },
    button2:{
        paddingVertical:10,
        borderWidth:2,
        width:'48%',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:10,
        borderColor:selectedTheme.lineDivider,
        backgroundColor:COLORS.primary
    },
    buttonText:{
        ...FONTS.h3,
        color:selectedTheme.textColor
    },
    buttonText2:{
        ...FONTS.h3,
        color:COLORS.white
    }
})
export default styles;