import { StyleSheet } from "react-native";
import {
    COLORS,

} from '../../constants';
import { FONTS, SIZES } from "../../constants/theme";

const styles = (selectedTheme:any)=>StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:COLORS.primary
    },
    upperContainer:{
        flex:0.15,
        justifyContent:'center'
    },
    lowerContainer:{
        padding:10,
        flex:1,
        backgroundColor:selectedTheme.backgroundColor1,
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
    },
    innerUpperContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        paddingHorizontal:10
       
    },
    headerLeftIcon:{
        height:40,
        width:40,
        tintColor:selectedTheme.tintColor,
        resizeMode:'contain'
    },
    headerRightIcon:{
        height:30,
        width:30,
        tintColor:selectedTheme.tintColor,
        resizeMode:'contain'
    },
    profileImage:{
        borderRadius:180,
    },
    profileImageView:{
        
          marginTop:-SIZES.height*0.117/2,
         
         height:SIZES.height*0.117,
         width:SIZES.width*0.2,
         alignSelf:'center',
         alignItems:'center',
         justifyContent:'flex-end'
    },
    blueTickImage:{
        height:20,
        resizeMode:'contain',
        width:20,
        marginBottom:-10,
    },
    headText:{
        ...FONTS.h2,
        color:selectedTheme.textColor,
        textAlign:'center',
        paddingTop:20,
    },
    postText:{
        ...FONTS.h3,
        color:selectedTheme.textColor3,
        textAlign:'center',
        paddingVertical:5,
    },
    followButton:{
        alignSelf:'center',
        paddingHorizontal:10,
        paddingVertical:5,
        borderColor:COLORS.primary,
        borderWidth:2,
        borderRadius:15
    },
    followText:{
        ...FONTS.h3,
        color:COLORS.primary
    },
    lowerUpContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginVertical:10,
    },
    followerContainer:{
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#FDF5E6',
        padding:10,
        width:95/3+'%',
        borderRadius:10,
    },
    reviewContainer:{
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#FFDAB9',
        padding:10,
        width:95/3+'%',
        borderRadius:10,
    },
    totalStudentsContainer:{
        
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#AFEEEE',
        padding:10,
        width:95/3+'%',
        borderRadius:10,
    },
    titleText:{
        ...FONTS.h2,
        color:COLORS.black,
     
    },
    subTitleText:{
        ...FONTS.h4,
        color:COLORS.gray90,
    },
    headingText:{
        ...FONTS.h2,
        color:selectedTheme.textColor
    },
    labelText:{
        ...FONTS.h4,
        color:selectedTheme.textColor3
    },
    labelText2:{
        ...FONTS.h4,
        color:selectedTheme.textColor
    },
    aboutmeContainer:{
        borderBottomWidth:1,
        borderColor:selectedTheme.lineDivider,
        paddingTop:10,
        paddingBottom:15,
    },
    renderContainer3:{
        flexDirection:'row',
        marginVertical:10,
    },
    render3MainImage:{
        width:SIZES.width*0.35,
        padding:10
        
    },
    render3FavouriteButton:{
        alignSelf:'flex-end',
        padding:5,
        backgroundColor:COLORS.white,
        borderRadius:5
    },
    heartIcon:{
        height:20,
        width:20,
        resizeMode:'contain'
    },
    render3TitleText:{
        paddingHorizontal:10,
        width:SIZES.width*0.5,
        ...FONTS.h3,
        color:selectedTheme.textColor
    },
    render3InnerContainer:{
        flexDirection:'row',
        alignItems:'center'
    },
    render3InstructorText:{
        paddingLeft:10,
        ...FONTS.h4,
        color:selectedTheme.textColor3
    },
    render3DurationContainer:{
        flexDirection:'row',
        paddingLeft:5,
        alignItems:'center'
    },
    render3ClockIcon:{
        height:18,
        width:18,
        resizeMode:'contain',
        tintColor:COLORS.gray40
    },
    render3DurationText:{
        paddingLeft:5,
        ...FONTS.h4,
        color:selectedTheme.textColor3
    },
    render3InnerLowerContainer:{
        flexDirection:'row',
        paddingLeft:10,
        alignItems:'center'
    },
    render3RatingIcon:{
        height:20,
        width:20,
        resizeMode:'contain'
    },
    render3RatingContainer:{
        flexDirection:'row',
        paddingLeft:10,
        alignItems:'center'
    },
    render3ItemSeprator:{
        marginVertical:"1%"
    },
    render3PriceText:{
        ...FONTS.h2,
        color:COLORS.primary
    },
    render3RatingText:{
        ...FONTS.h4,
        paddingLeft:5,
        color:selectedTheme.textColor
    },
    myCoursesUpContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        paddingVertical:10,
    },
    seeAllButton:{
        paddingVertical:5,
        paddingHorizontal:8,
        backgroundColor:COLORS.primary,
        borderRadius:15
    },
    seeAllText:{
        color:COLORS.white,
        ...FONTS.h3
    },
    mycoursesContainer:{
        marginVertical:10,
        borderBottomWidth:1,
        borderColor:selectedTheme.lineDivider,
        paddingBottom:10,   
    },
    studentReviewContainer:{
        marginVertical:10,
        borderBottomWidth:1,
        borderColor:selectedTheme.lineDivider,
        paddingBottom:15,

    },
    studentReviewUpContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        paddingVertical:10,
    },
    renderStudentContainer:{
        borderRadius:10,
        padding:10,
        flexDirection:'row',
        width:SIZES.width*0.6,
   
        backgroundColor:selectedTheme.backgroundColor8
    },
    renderLeftStudentContainer:{
        paddingLeft:10,
        flex:1,
    },
    studentImage:{
        height:SIZES.height*0.08,
        width:SIZES.width*0.14,
        borderRadius:180,
    },
    studentSeprator:{
        margin:5
    },
    socialMediaButton:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginVertical:10,
    },
    innerSocialMediaContainer:{
        flexDirection:'row',
        alignItems:'center'
    },
    socialMediaIcon:{
        height:40,
        width:40,
        resizeMode:'contain',
        marginRight:10,
    },
    socialMediaText:{
        color:selectedTheme.textColor3,
        ...FONTS.h3
    },
    leftArrowIcon:{
        height:30,
        width:30,
        resizeMode:'contain',
        tintColor:COLORS.gray40
    }

})

export default styles;