
const string ={
    profile:"Profile",
    changePassword:"Change Password",
    communicationPreference:"Communication Preferences",
    changeLanguage:"Change Language",
    signOut:"Sign Out",
    manageAccount:'MANAGE ACCOUNT',
    yourCourses: 'Your Courses',
    continueLearning:'Continue Learning',
    camera:"Camera",
    gallery:"Gallery",
    cancel:'cancel',
    personalInformation:'Personal Information',
    contact:'Contact',
    mailingAddress:'Mailing Address',
    email:"Email",
    homePhone:"Home Phone",
    workPhone:"Work Phone",
    mobilePhone:"Mobile Phone",
    firstName:"First Name",
    lastName:'Last Name',
    gender:'Gender',
    address:'Address',
    save:'Save',
    edit:'Edit',
    lastViewedModules:'LAST VIEWED MODULE',
    detoxYourLife:"Detox Your Life",
    resume:'Resume',
    moduleText:"This first module is all about setting you up...",
    modules:'Modules',
    filter:'Filters',
    title:'Title',
    bookmarks:'Bookmarks',
    unbookmarks:'Unbookmarks',
    or:'or',
}

export default string;