import { StyleSheet } from "react-native";
import {
    constants,
    theme,
    COLORS,
    darkTheme,
    lightTheme,
    images,
    icons,
    dummyData,

} from '../../constants';
import { FONTS, SIZES } from "../../constants/theme";



const styles=(selectedTheme:any)=>StyleSheet.create({
        container:{
            flex:1,
            backgroundColor: selectedTheme.backgroundColor1,
            padding:10,
        },
        header:{
            flexDirection:'row',
            justifyContent:'space-between',
            alignItems:'center'
        },
        imageBackground:{
            marginVertical:10,
            padding:10,
        },
        howToText:{
           fontSize:30,
        color:COLORS.white
        },
        brandText:{
            ...FONTS.h1,
            color:COLORS.white
        },
        bytText:{
            ...FONTS.h3,
            color:COLORS.white
        },
        startLearningImage:{
            marginTop:10,
            alignSelf:'flex-end'
        },

        notificationIcon:{
            height:30,
            width:30,
            resizeMode:'contain',
            tintColor:selectedTheme.tintColor
        },
        headerNameText:{
            ...FONTS.h2,
            color:selectedTheme.textColor
        },
        headerDateText:{
            ...FONTS.h4,
            color:selectedTheme.textColor6
        },
        render1FlatList:{
            marginVertical:10,
            borderBottomWidth:1,
            borderColor:COLORS.gray40
        },
        renderContainer1:{
            flex:1,
        },
        render1MainImage:{
        width:SIZES.width*0.7,
        height:SIZES.height*0.2,
        borderRadius:10
        },
        render1InnerContainer:{
            flexDirection:'row',
            marginVertical:10,
        },
        playIcon:{
            resizeMode:'contain',
            height:40,
            width:40
        },
        render1TitleText:{
            ...FONTS.h3,
            fontWeight:'800',
            width:SIZES.width*0.5,
            paddingHorizontal:10,
            color:selectedTheme.textColor
        },
        render1TimeContainer:{
            flexDirection:'row',
            alignItems:'center',
            paddingHorizontal:10,
            paddingTop:5
        },
        timeIcon:{
            resizeMode:'contain',
            height:20,
            width:20,
            tintColor:COLORS.gray40
        },
        render1DurationText:{
            ...FONTS.h4,
            paddingLeft:5,
            color:COLORS.gray40
        },
        render1ItemSeprator:{
            margin:5
        },
        titleText:{
            ...FONTS.h2,
            color:selectedTheme.textColor
        },
        seeAllButton:{
            marginRight:10,
            backgroundColor:COLORS.primary,
            justifyContent:'center',
            alignItems:'center',
            padding:5,
            paddingHorizontal:15,
            borderRadius:15,
        },
        seeAllButtonText:{
            ...FONTS.h3,
            color:COLORS.white
        },
        render2Container:{
            width:SIZES.width*0.55,
            height:SIZES.height*0.2,
            justifyContent:'flex-end',
            padding:10
        },
        render2FlatlistInnerContainer:{
            marginVertical:10,
            flexDirection:'row',
            justifyContent:'space-between'
        },
    
        render2TitleText:{
            ...FONTS.h2,
            color:COLORS.white,
            paddingBottom:10
        },
        render3FlatlistInnerContainer:{
            marginVertical:10,
            flexDirection:'row',
            justifyContent:'space-between'
        },

        renderContainer3:{
            flexDirection:'row'
        },
        render3MainImage:{
            width:SIZES.width*0.35,
            padding:10
            
        },
        render3FavouriteButton:{
            alignSelf:'flex-end',
            padding:5,
            backgroundColor:COLORS.white,
            borderRadius:5
        },
        heartIcon:{
            height:20,
            width:20,
            resizeMode:'contain'
        },
        render3TitleText:{
            paddingHorizontal:10,
            width:SIZES.width*0.5,
            ...FONTS.h3,
            color:selectedTheme.textColor
        },
        render3InnerContainer:{
            flexDirection:'row',
            alignItems:'center'
        },
        render3InstructorText:{
            paddingLeft:10,
            ...FONTS.h4,
            color:selectedTheme.textColor3
        },
        render3DurationContainer:{
            flexDirection:'row',
            paddingLeft:5,
            alignItems:'center'
        },
        render3ClockIcon:{
            height:18,
            width:18,
            resizeMode:'contain',
            tintColor:COLORS.gray40
        },
        render3DurationText:{
            paddingLeft:5,
            ...FONTS.h4,
            color:selectedTheme.textColor3
        },
        render3InnerLowerContainer:{
            flexDirection:'row',
            paddingLeft:10,
            alignItems:'center'
        },
        render3RatingIcon:{
            height:20,
            width:20,
            resizeMode:'contain'
        },
        render3RatingContainer:{
            flexDirection:'row',
            paddingLeft:10,
            alignItems:'center'
        },
        render3ItemSeprator:{
            marginVertical:"1%"
        },
        render3PriceText:{
            ...FONTS.h2,
            color:COLORS.primary
        },
        render3RatingText:{
            ...FONTS.h4,
            paddingLeft:5,
            color:selectedTheme.textColor
        }
    }
)

export default styles;